#!/bin/bash
# bash script for starting robot controller code in debug mode.

SCRIPTPATH=/home/create/apriltag/python/robot_controller.py

#echo "Starting robot script..."
sudo nice -n -5 python3 $SCRIPTPATH
